```{r}
library(car)
library(lmtest)
library(GGally)
```



```{r}
LE = read.csv("https://raw.githubusercontent.com/ethan2411/Data-603-604/main/Life%20Expectancy%20Data.csv")
LE = na.omit(LE)
head(LE)
```
```{r}
test.lm <- lm(Life.expectancy ~ factor(Country) + factor(Status) + Adult.Mortality + infant.deaths + Alcohol + percentage.expenditure + Hepatitis.B  + Measles + BMI + under.five.deaths + Polio + Total.expenditure + Diphtheria + HIV.AIDS + thinness.5.9.years+ Income.composition.of.resources + Schooling + GDP + Population + thinness..1.19.years, data = LE)
summary(test.lm)
```

```{r}
LE2 = subset(LE, select =- c(Year, Country))
LE2 = na.omit(LE2)
head(LE2)
```

```{r}
LE.lm <- lm(Life.expectancy ~ factor(Status) + Adult.Mortality + infant.deaths + Alcohol + percentage.expenditure + Hepatitis.B  + Measles + BMI + under.five.deaths + Polio + Total.expenditure + Diphtheria + HIV.AIDS + thinness.5.9.years+ Income.composition.of.resources + Schooling + GDP + Population + thinness..1.19.years, data = LE2)
summary(LE.lm)
```

REMOVING GDP, Population, and thinness 1-19 (to see if that's chill)
```{r}
LE.reduced <- lm(Life.expectancy ~ factor(Status) + Adult.Mortality + infant.deaths + Alcohol + percentage.expenditure + Hepatitis.B  + Measles + BMI + under.five.deaths + Polio + Total.expenditure + Diphtheria + HIV.AIDS + thinness.5.9.years+ Income.composition.of.resources + Schooling , data = LE2)
summary(LE.reduced)
anova(LE.lm, LE.reduced)
```
REMOVE MEASLES Hepatitis b, and Polio

```{r}
LE.reduced2 <- lm(Life.expectancy ~ factor(Status) + Adult.Mortality + infant.deaths + Alcohol + percentage.expenditure + BMI + under.five.deaths + Total.expenditure + Diphtheria + HIV.AIDS + thinness.5.9.years+ Income.composition.of.resources + Schooling , data = LE2)
summary(LE.reduced2)
anova(LE.reduced2, LE.reduced)
```
remove total expenditure 

```{r}
LE.reduced3 <- lm(Life.expectancy ~ factor(Status) + Adult.Mortality + infant.deaths + Alcohol + percentage.expenditure + BMI + under.five.deaths + Diphtheria + HIV.AIDS + thinness.5.9.years+ Income.composition.of.resources + Schooling , data = LE2)
summary(LE.reduced3)
anova(LE.reduced3, LE.reduced)
```
```{r}
plot(LE.reduced3)
```
```{r}
bptest(LE.reduced3)
shapiro.test(LE2$Life.expectancy)
```
```{r}
vif(LE.reduced3)
```

DROPPING THE FUCK OUT OF under.five.deaths

```{r}
LE.reduced4 <- lm(Life.expectancy ~ factor(Status) + Adult.Mortality + Alcohol + percentage.expenditure + BMI + infant.deaths + Diphtheria + HIV.AIDS + thinness.5.9.years+ Income.composition.of.resources + Schooling , data = LE2)
summary(LE.reduced4)
vif(LE.reduced4)
```

```{r}
LE.reduced5 <- lm(Life.expectancy ~ factor(Status) + Adult.Mortality + Alcohol + percentage.expenditure + BMI + infant.deaths + Diphtheria + HIV.AIDS + Income.composition.of.resources + Schooling , data = LE2)
summary(LE.reduced5)
```

```{r}
plot(LE.reduced5)
```

#Checking for higher order variables

```{r}
#making dataframe with only variables we're using for the regression. 
LE3 <- subset(LE2, select = c(Adult.Mortality, Alcohol, percentage.expenditure, BMI, infant.deaths, Diphtheria, HIV.AIDS, Income.composition.of.resources, Schooling, Life.expectancy))
```


```{r}
pairs(LE3)
```


AIDS looks to be higher order 

```{r}
LE.power <- lm(Life.expectancy ~ factor(Status)  + Adult.Mortality + Alcohol + percentage.expenditure + BMI + infant.deaths + Diphtheria + poly(HIV.AIDS,5) + Income.composition.of.resources + Schooling , data = LE2)
summary(LE.power)
bptest(LE.power)
plot(LE.power)
```

REMOVE ALCOHOL

```{r}
LE.power2 <- lm(Life.expectancy ~ factor(Status)  + Adult.Mortality + percentage.expenditure + BMI + infant.deaths + Diphtheria + poly(HIV.AIDS,5) + Income.composition.of.resources + Schooling , data = LE2)
summary(LE.power2)
bptest(LE.power2)
plot(LE.power2)
```
















#Making an interactions model

```{r}
LE.interactions <- lm(Life.expectancy ~ (factor(Status) + Adult.Mortality + Alcohol + percentage.expenditure + BMI + infant.deaths + Diphtheria + HIV.AIDS + Income.composition.of.resources + Schooling)^2, data = LE2)
summary(LE.interactions)
```


#Using stepwise to reduce the model
```{r}
model_step = step(LE.interactions, direction = "both")
summary(model_step)
```
```{r}
summary(model_step)
plot(model_step)
bptest(model_step)
```

#LOG transformation

```{r}
log.lm <- lm(log(Life.expectancy) ~ factor(Status) + Adult.Mortality + 
    Alcohol + percentage.expenditure + BMI + infant.deaths + 
    Diphtheria + HIV.AIDS + Income.composition.of.resources + 
    Schooling + factor(Status):Adult.Mortality + factor(Status):Alcohol + 
    factor(Status):percentage.expenditure + factor(Status):BMI + 
    factor(Status):Income.composition.of.resources + factor(Status):Schooling + 
    Adult.Mortality:Alcohol + Adult.Mortality:BMI + Adult.Mortality:infant.deaths + 
    Adult.Mortality:Diphtheria + Adult.Mortality:HIV.AIDS + Adult.Mortality:Income.composition.of.resources + 
    Adult.Mortality:Schooling + Alcohol:percentage.expenditure + 
    Alcohol:HIV.AIDS + Alcohol:Income.composition.of.resources + 
    Alcohol:Schooling + percentage.expenditure:infant.deaths + 
    percentage.expenditure:Income.composition.of.resources + 
    percentage.expenditure:Schooling + BMI:infant.deaths + BMI:Diphtheria + 
    BMI:Income.composition.of.resources + BMI:Schooling + infant.deaths:Diphtheria + 
    infant.deaths:Income.composition.of.resources + infant.deaths:Schooling + 
    Diphtheria:Income.composition.of.resources + Diphtheria:Schooling + 
    HIV.AIDS:Schooling, data = LE2)

summary(log.lm)
plot(log.lm)
bptest(log.lm)
```

```{r}
library(MASS)
bc = boxcox(model_step,lambda=seq(-1,1))

bestlambda=bc$x[which(bc$y==max(bc$y))]
bestlambda
```

```{r}
sqrt.lm <- lm(sqrt(Life.expectancy) ~ factor(Status) + Adult.Mortality + 
    Alcohol + percentage.expenditure + BMI + infant.deaths + 
    Diphtheria + HIV.AIDS + Income.composition.of.resources + 
    Schooling + factor(Status):Adult.Mortality + factor(Status):Alcohol + 
    factor(Status):percentage.expenditure + factor(Status):BMI + 
    factor(Status):Income.composition.of.resources + factor(Status):Schooling + 
    Adult.Mortality:Alcohol + Adult.Mortality:BMI + Adult.Mortality:infant.deaths + 
    Adult.Mortality:Diphtheria + Adult.Mortality:HIV.AIDS + Adult.Mortality:Income.composition.of.resources + 
    Adult.Mortality:Schooling + Alcohol:percentage.expenditure + 
    Alcohol:HIV.AIDS + Alcohol:Income.composition.of.resources + 
    Alcohol:Schooling + percentage.expenditure:infant.deaths + 
    percentage.expenditure:Income.composition.of.resources + 
    percentage.expenditure:Schooling + BMI:infant.deaths + BMI:Diphtheria + 
    BMI:Income.composition.of.resources + BMI:Schooling + infant.deaths:Diphtheria + 
    infant.deaths:Income.composition.of.resources + infant.deaths:Schooling + 
    Diphtheria:Income.composition.of.resources + Diphtheria:Schooling + 
    HIV.AIDS:Schooling, data = LE2)

summary(sqrt.lm)
plot(sqrt.lm)
bptest(sqrt.lm)
```

```{r}

test.lm = lm(Life.expectancy ~  factor(Status) + Alcohol + Hepatitis.B  + Measles + BMI + Polio + Diphtheria + HIV.AIDS, data = LE)
summary(test.lm)

```

```{r}

vif(test.lm)


```

```{r}

test.lm2 = lm(Life.expectancy ~  factor(Status) + Alcohol + Hepatitis.B + BMI + Polio + Diphtheria + HIV.AIDS, data = LE)
summary(test.lm2)

plot(test.lm2)

```

```{r}


test.lmint = lm(Life.expectancy ~  (factor(Status) + Alcohol + Hepatitis.B + BMI + Polio + Diphtheria + HIV.AIDS)^2, data = LE)
summary(test.lmint)

test.lmintred = step(test.lmint, method = "BOTH")




```

```{r}



summary(test.lmintred)


```

```{r}
test.lmhigher = lm(Life.expectancy ~  factor(Status) + Alcohol + Hepatitis.B + BMI + Polio + Diphtheria + HIV.AIDS + I(HIV.AIDS^2) + I(HIV.AIDS^3) + I(HIV.AIDS^4) + factor(Status):Alcohol + factor(Status):Hepatitis.B + factor(Status):BMI + factor(Status):Diphtheria + Alcohol:Hepatitis.B + Alcohol:Diphtheria + Alcohol:Hepatitis.B + Alcohol:Diphtheria +  Alcohol:HIV.AIDS + Hepatitis.B:BMI + Hepatitis.B:Diphtheria + BMI:Polio + BMI:Diphtheria + Polio:Diphtheria + Diphtheria:HIV.AIDS, data = LE) 

bptest(test.lmhigher)

anova(test.lmhigher, test.lmintred)
```




```{r}
ggpairs(test.lmintred)

```


```{r}
plot(test.lmhigher)

summary(test.lmhigher)

```

```{r}
library(MASS)
bc = boxcox(test.lmhigher, lambda=seq(-1,1))

bestlambda = bc$x[which(bc$y==max(bc$y))]
bestlambda


```


```{r}
lev=hatvalues(test.lmhigher)
p = length(coef(test.lmhigher))
n = nrow(LE)
outlier2p = lev[lev>(2*p/n)]
outlier3p = lev[lev>(3*p/n)]
print("h_I>3p/n, outliers are")
print(outlier2p)

rows_remove = which(lev>(2*p/n))
print(outlier2plist)

LE_no_outliers = LE[-rows_remove, ]
head(LE_no_outliers)

nrow(LE)
nrow(LE_no_outliers)
```

```{r}
test.lm2 = lm(Life.expectancy ~  factor(Status) + Alcohol + Hepatitis.B  + Measles + BMI + Polio + Diphtheria + HIV.AIDS, data = LE_no_outliers)
summary(test.lm2)



```

```{r}

test.lm2red = lm(Life.expectancy ~  factor(Status) + Alcohol + Hepatitis.B  + Measles + BMI + Diphtheria + HIV.AIDS, data = LE_no_outliers)
summary(test.lm2red)

```

```{r}
test.lm2int = lm(Life.expectancy ~  (factor(Status) + Alcohol + Hepatitis.B  + Measles + BMI + Diphtheria + HIV.AIDS)^2, data = LE_no_outliers)
summary(test.lm2int)

step_model2 = step(test.lm2int)
summary(step_model2)

```

```{r}

test.lm2higher = lm(Life.expectancy ~  factor(Status) + Alcohol + Hepatitis.B  + Measles + I(Measles^2) + BMI + Diphtheria + HIV.AIDS + I(HIV.AIDS^2) + I(HIV.AIDS^3) + factor(Status):BMI + factor(Status):Diphtheria + Alcohol:Hepatitis.B + Alcohol:Measles + Alcohol:Diphtheria + Hepatitis.B:Diphtheria + Measles:Diphtheria + Measles:HIV.AIDS + BMI:Diphtheria + Diphtheria:HIV.AIDS,  data = LE_no_outliers)

summary(test.lm2higher)

bptest(test.lm2higher)


shapiro.test(residuals(test.lm2higher))


plot(test.lm2higher)


bc = boxcox(test.lm2higher, lambda=seq(-1,1))

bestlambda = bc$x[which(bc$y==max(bc$y))]
bestlambda



```

```{r}
ggpairs(test.lm2higher)


```















