# Data 603 Term Project

```{r}
library(olsrr)
```

## Loading Data

```{r}
df = read.csv('https://raw.githubusercontent.com/ethan2411/Data-603-604/main/603%20Data/500_Cities__Census_Tract-level_Data__GIS_Friendly_Format___2019_release_20231106.csv')
head(df)


```

## Feature Selection

```{r}
#removing all data but the "prevalence" measures for calculations. 
#df.calcs = df frame used for calculations. 
df.calcs <- subset(df, select =- c(StateAbbr, PlaceName, PlaceFIPS, TractFIPS,Place_TractID,Population2010, ACCESS2_Crude95CI, ARTHRITIS_Crude95CI, BINGE_Crude95CI, BPHIGH_Crude95CI, BPMED_Crude95CI, CANCER_Crude95CI, CASTHMA_Crude95CI, CHD_Crude95CI, CHECKUP_Crude95CI, CHOLSCREEN_Crude95CI, COLON_SCREEN_Crude95CI,COPD_Crude95CI, COREM_Crude95CI, COREW_Crude95CI, CSMOKING_Crude95CI, DENTAL_Crude95CI,DIABETES_Crude95CI,  HIGHCHOL_Crude95CI, KIDNEY_Crude95CI, LPA_Crude95CI, MAMMOUSE_Crude95CI, MHLTH_Crude95CI, OBESITY_Crude95CI, PAPTEST_Crude95CI, PHLTH_Crude95CI, SLEEP_Crude95CI, STROKE_Crude95CI, TEETHLOST_Crude95CI, Geolocation))

head(df.calcs)
```

```{r}
#narrowing the factors to only be unhealthy habits and preventative measures
df.unhealthy.precitors <- df.calcs <- subset(df.calcs, select =- c(ARTHRITIS_CrudePrev, BPHIGH_CrudePrev, CASTHMA_CrudePrev, CHD_CrudePrev, COPD_CrudePrev, DIABETES_CrudePrev, HIGHCHOL_CrudePrev, KIDNEY_CrudePrev, MAMMOUSE_CrudePrev, MHLTH_CrudePrev, PHLTH_CrudePrev, STROKE_CrudePrev))
head(df.unhealthy.precitors)
```

```{r}
#narrowing the dataset even further to just predictive variables
cancer.pred.only <- subset(df.unhealthy.precitors,  select =- c(BINGE_CrudePrev, CSMOKING_CrudePrev, LPA_CrudePrev, OBESITY_CrudePrev, SLEEP_CrudePrev))
head(cancer.pred.only)
```

## Full Linear Model

```{r}
cancer.lm <- lm(CANCER_CrudePrev ~ ., data = cancer.pred.only)
summary(cancer.lm)
```

```{r}
#removing ACCESS2_CrudePrev since not statistically significant
cancer.reduced <- lm(CANCER_CrudePrev ~ BPMED_CrudePrev + CHECKUP_CrudePrev + CHOLSCREEN_CrudePrev + COLON_SCREEN_CrudePrev + COREM_CrudePrev + COREW_CrudePrev  + DENTAL_CrudePrev + PAPTEST_CrudePrev + TEETHLOST_CrudePrev, data = df.unhealthy.precitors)

summary(cancer.reduced)

anova(cancer.lm, cancer.reduced)


```

```{r}
plot(cancer.reduced)
?VIF

```

```{r}
library(car)
vif(lm(CANCER_CrudePrev ~ BPMED_CrudePrev + CHECKUP_CrudePrev + CHOLSCREEN_CrudePrev + COLON_SCREEN_CrudePrev + COREM_CrudePrev + COREW_CrudePrev  + DENTAL_CrudePrev + PAPTEST_CrudePrev + TEETHLOST_CrudePrev, data = df.unhealthy.precitors))


```

```{r}
pairs(cancer.pred.only)
```

Given the ANOVA output, we can drop ACCESS2_CrudePrev.

```{r}
cancer.interactions <- lm(CANCER_CrudePrev ~ (BPMED_CrudePrev + CHECKUP_CrudePrev + CHOLSCREEN_CrudePrev + COLON_SCREEN_CrudePrev + COREM_CrudePrev + COREW_CrudePrev  + DENTAL_CrudePrev + PAPTEST_CrudePrev + TEETHLOST_CrudePrev)^2, data = df.unhealthy.precitors)

summary(cancer.interactions)
```

## Stepwise Model

```{r}
model_step <- step(cancer.pred.only.interactions, direction = "both")

```

```{r}
summary(model_step)
```

```{r}
rounded_coefficients <- round(coefficients(model_step), 6)  # Round coefficients to 6 digits

# Construct the formula with rounded coefficients
formula_str <- paste0("y ~ ", 
                     round(rounded_coefficients[1], 6), 
                     "", 
                     paste(sprintf(" %+.6f*%s ", 
                                   rounded_coefficients[-1], 
                                   names(rounded_coefficients[-1])), 
                           collapse="")
                     )

# Convert the formula string into a formula object
formula_with_rounded_coefficients <- as.formula(formula_str)

# Print the formula
print(formula_with_rounded_coefficients)
```

## Model Assumptions

```{r}
#linearity assumption
library(ggplot2)
ggplot(model_step, aes(x=.fitted, y=.resid)) +
geom_point() + geom_smooth()+
geom_hline(yintercept = 0)
```

```{r}
plot(model_step)

```

### Box Cox Transformation

```{r}
library(MASS)
bc = boxcox(model_step,lambda=seq(-1,1))

cancer.pred.new = cancer.pred.only %>%
  mutate(CANCER_boxcox = (CANCER_CrudePrev^lambda - 1)/lambda)

head(cancer.pred.new)
```

#### Interactions with box cox

```{r}
new = lm(formula = CANCER_boxcox ~ BPMED_CrudePrev + CHECKUP_CrudePrev + 
    CHOLSCREEN_CrudePrev + COLON_SCREEN_CrudePrev + COREM_CrudePrev + 
    COREW_CrudePrev + DENTAL_CrudePrev + PAPTEST_CrudePrev + 
    TEETHLOST_CrudePrev + BPMED_CrudePrev:CHECKUP_CrudePrev + 
    BPMED_CrudePrev:CHOLSCREEN_CrudePrev + BPMED_CrudePrev:COLON_SCREEN_CrudePrev + 
    BPMED_CrudePrev:COREM_CrudePrev + BPMED_CrudePrev:COREW_CrudePrev + 
    BPMED_CrudePrev:PAPTEST_CrudePrev + BPMED_CrudePrev:TEETHLOST_CrudePrev + 
    CHECKUP_CrudePrev:CHOLSCREEN_CrudePrev + CHECKUP_CrudePrev:COLON_SCREEN_CrudePrev + 
    CHECKUP_CrudePrev:COREM_CrudePrev + CHECKUP_CrudePrev:DENTAL_CrudePrev + 
    CHECKUP_CrudePrev:PAPTEST_CrudePrev + CHECKUP_CrudePrev:TEETHLOST_CrudePrev + 
    CHOLSCREEN_CrudePrev:COLON_SCREEN_CrudePrev + CHOLSCREEN_CrudePrev:COREM_CrudePrev + 
    CHOLSCREEN_CrudePrev:COREW_CrudePrev + CHOLSCREEN_CrudePrev:DENTAL_CrudePrev + 
    CHOLSCREEN_CrudePrev:PAPTEST_CrudePrev + CHOLSCREEN_CrudePrev:TEETHLOST_CrudePrev + 
    COLON_SCREEN_CrudePrev:COREW_CrudePrev + COLON_SCREEN_CrudePrev:DENTAL_CrudePrev + 
    COLON_SCREEN_CrudePrev:PAPTEST_CrudePrev + COLON_SCREEN_CrudePrev:TEETHLOST_CrudePrev + 
    COREM_CrudePrev:COREW_CrudePrev + COREM_CrudePrev:DENTAL_CrudePrev + 
    COREM_CrudePrev:PAPTEST_CrudePrev + COREW_CrudePrev:DENTAL_CrudePrev + 
    COREW_CrudePrev:PAPTEST_CrudePrev + COREW_CrudePrev:TEETHLOST_CrudePrev + 
    DENTAL_CrudePrev:PAPTEST_CrudePrev + DENTAL_CrudePrev:TEETHLOST_CrudePrev + 
    PAPTEST_CrudePrev:TEETHLOST_CrudePrev, data = cancer.pred.new)

plot(new)
```


```{r}
library(lmtest)
bptest(new)
```








